//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaMEdica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> Cedula { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Email { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> IDSeguro { get; set; }
    
        public virtual Seguro Seguro { get; set; }
    }
}
